name: messenger_chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.0
  firebase_storage: ^10.3.11
  flutter_screenutil: ^5.5.4
  lottie: ^1.4.3
  google_fonts: ^3.0.1
  auto_route: ^5.0.1
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.10.0
  country_picker: ^2.0.16
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  image_picker: ^0.8.6
  flutter_contacts: ^1.1.5
  uuid: ^3.0.6
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  cached_video_player: ^2.0.3
  emoji_picker_flutter: ^1.5.0
  flutter_sound: ^9.2.13
  permission_handler: ^9.2.0
  path_provider: ^2.0.11
  audioplayers: ^1.1.1
  swipe_to: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.5.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/landingPage/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
